### ISSUE TITLE
2.3.2 findTeddyBear.java

### ISSUE THREAD

**Issue by 5ubstitute** [ItsDominator/Karel_Solutions#1]
The error "cannot move through wall" should usually not appear because turnLeft is executed before moveForward.
The only exception is when you are standing in a corner and have to turn left twice before you can move forward.
Thank you for your feedback. Replacing my if with a while would have been easier. 😉

**Comment by ItsDominator** [comment]
Thanks for the tip - I think with "while" it is an easier way compared to my previous solution.
